### ISSUE TITLE
Mouse Cursor Positioning

### ISSUE THREAD

**Issue by JohnCampionJr** [bcakmakoglu/revue-draggable#340]
**Describe the bug**
Hi and thank you for this project.  Should it be working with svg elements?  I'm trying to add draggable to a <rect> element in an SVG surface but it will not work.

**Comment by JohnCampionJr** [comment]
I was able to get SVG elements working (error on my part) but the mouse cursor moves faster than the drag, so after dragging the cursor is outside the element being dragged.

I will try to create a minimal repro if I can.

**Comment by bcakmakoglu** [comment]
Hey @JohnCampionJr and thank you for the report.
If you can provide me with a minimal repro that would be great 😄

**Comment by JohnCampionJr** [comment]
@bcakmakoglu Here you go:
https://stackblitz.com/edit/github-gqqj1o?file=pages/draggable.vue

Drag that svg box around and see how the pointer behaves.  The points need to be scaled to the svg surface.

**Comment by bcakmakoglu** [comment]
Mh... other than the fact, that the `rect` color needed a change so it's actually visible against the svg background, I can't seem to reproduce the issue.

Here's a quick clip I just made using the exact same code you provided, no modifications (other than the rect color).

https://user-images.githubusercontent.com/78412429/188729240-4d70817b-619e-4223-8a43-c54e80b9248f.mov

Looks exactly as intended to me.

Although, if you have a certain "zoom" factor applied to your elements, it is necessary to pass that to draggable as well of course - and you can, there is a prop called `scale` which accepts a number-type value.

**Comment by bcakmakoglu** [comment]
@JohnCampionJr 
So yeah, as mentioned - use `scale` and find the proper scaling value for your viewbox, that's simply it. I can't really tell you what it's supposed to be, as it depends on your actual implementation but you could play around with it and see what works.

Here's an example.

**Comment by JohnCampionJr** [comment]
I wonder if it's because I'm on a high-res screen with scaling?

https://clipchamp.com/watch/6UK5bA8uyjW
