### ISSUE TITLE
Controlled Position not working

### ISSUE THREAD

**Issue by CubE135** [bcakmakoglu/revue-draggable#350]
**Describe the bug**
As i am trying to control the position of a draggable element, it does not seem to work properly. I tried everything i could imagine, read through the source code of the example etc. but i can not get it to work.

**To Reproduce**
1. Use this code: 
![image](https://user-images.githubusercontent.com/8761463/193877796-56321905-e0de-4cef-9f79-e0154a76a481.png)
(Also not working without any style or classes)
2. Run it
3. Click on the "I can be clicked" box.
4. Watch as nothing will happen.

**Expected behavior**
When clicking the "I can be clicked" box, the "I can be dragged" Box should change its position.

**Screenshots**
![image](https://user-images.githubusercontent.com/8761463/193878017-47072852-6d25-45d6-af34-2d6826c1bda0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 105.0.5195.127

**Additional context**
Im using nuxt, this is my draggable plugin:
![image](https://user-images.githubusercontent.com/8761463/193878299-18c2d04a-6c8a-4bc6-8c6e-ab23d6a3eada.png)

**Comment by bcakmakoglu** [comment]
Sorry I am a little busy right now but I will get back to you as soon as I can :)

Just to make sure: You're using Vue2 right?

**Comment by CubE135** [comment]
Yes, i am :)

**Comment by bcakmakoglu** [comment]
Sorry for the very late update, I have been super busy with different projects but I will take a look into this problem now 👍

**Comment by bcakmakoglu** [comment]
I can't seem to properly reproduce this issue, could you provide me with a sandbox for this? @CubE135

**Comment by CubE135** [comment]
> I can't seem to properly reproduce this issue, could you provide me with a sandbox for this? @CubE135

Sure, here you go: https://codesandbox.io/p/sandbox/draggable-c3jxkw

**Comment by bcakmakoglu** [comment]
Alright so after a lot of debugging and having forgotten this issue: Can you try replacing the controlledPosition object completely instead of mutating it's x and y value?

So instead of this
```ts
controlledPosition.x = 100
```

Do this
```ts
controlledPosition = { ...controlledPosition, x: 100 }
```

Then it should work as expected 😅

**Comment by CubE135** [comment]
Hey :)
As time has gone by, i was able to find a different solution for my problem.
But anyways, im glad to hear that you got the issue resolved :)
