### ISSUE TITLE
How can I stop the drgging using a function?

### ISSUE THREAD

**Issue by XxDraggy** [bcakmakoglu/revue-draggable#384]
I'm using this Plugin for just a few weeks now, and I have a question:
is there any way two stop the dragging of an object using a function? My sample is this:
![code](https://user-images.githubusercontent.com/96829537/211206684-20c0a172-1b2b-4a94-8cef-1f383a0138ae.png)
I'm using Vue 3 and this is my plugin init:
![code2](https://user-images.githubusercontent.com/96829537/211206799-6d813766-e27d-4037-ba22-2522656f8c8b.png)

**Comment by bcakmakoglu** [comment]
You can bind a callback function to the `drag` prop, which, if it returns `false` will cancel the action.
Same for `start` and `stop`.

For example

```
v-draggable="{ move: handleDrag }"

...

handleDrag(e: MouseTouchEvent, data: DraggableData) {
   if (/* some condition */) {
      return false // will cancel the move action
   }
}

**Comment by XxDraggy** [comment]
I'll trie it
Thanks for your reply

**Comment by XxDraggy** [comment]
But how can i implemend this in my sample-code?
![](https://user-images.githubusercontent.com/96829537/211206684-20c0a172-1b2b-4a94-8cef-1f383a0138ae.png)

**Comment by XxDraggy** [comment]
Should I do:
if(element.x >= 350) {
     return false;
}
?

**Comment by XxDraggy** [comment]
The sample above (if(element.x >= 350) {return false;}) doesn't work. I tried it with a log, and the log spamt.
But I didn't stop dragging.

**Comment by XxDraggy** [comment]
Yes, it works now. And thank you for you nice replies.
