### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toggle')

### ISSUE THREAD

**Issue by brenoepics** [bcakmakoglu/revue-draggable#400]
**Describe the bug**
revue-draggable.es.js:3 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toggle')
    at revue-draggable.es.js:3:7735
    at Array.forEach (<anonymous>)
    at b (revue-draggable.es.js:3:7679)
    at revue-draggable.es.js:3:8602
    at runtime-core.esm-bundler.js:2874:88
    at callWithErrorHandling (runtime-core.esm-bundler.js:193:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:201:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2854:19)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:369:40)
    at flushJobs (runtime-core.esm-bundler.js:407:5)

**To Reproduce**
1. Install on latest Vue 3 + TS and Vite

**Comment by brenoepics** [comment]
It works with 
```html
<template>
    <div v-draggable>
      <HelloWorld msg="Retro Overlay" />
    </div>
</template>
```

but not
```html
<Draggable>
    <div class="box">I use a wrapper</div>
  </Draggable>
```

**Comment by brenoepics** [comment]
error TS7016: Could not find a declaration file for module '@braks/revue-draggable'. '/home/runner/work/retro-overlay/retro-overlay/node_modules/@braks/revue-draggable/dist/revue-draggable.es.js' implicitly has an 'any' type.

Probably something related to this, I get dist only but no index.js as other dependencies

**Comment by bcakmakoglu** [comment]
Did you import the Draggable component?
The docs are built with Vite + Vue 3 and they use `<Draggable>` mostly and afaik the docs examples all still work 🤔
Do you, by chance, have a sandbox reproduction of this?

**Comment by bcakmakoglu** [comment]
@brenoepics ping - any chance for a repro on this?

**Comment by bcakmakoglu** [comment]
@brenoepics ping - otherwise I'll have to close the issue for now until I can get a repro for this :/

**Comment by bcakmakoglu** [comment]
closed due to insufficient info, please re-open with a repro if necessary.
