### ISSUE TITLE
Stop the movement when the mouse is outside the drag handle

### ISSUE THREAD

**Issue by SciManJD** [bcakmakoglu/revue-draggable#401]
Hi!
This is just a question, because I couldn't find an easy way to do it. I have some draggable objects with defined handle and bounds. When I drag an object and go outside the bounds, the object stays still caught by the mouse. I mean, if I'm outside of the right bound, but I move the mouse up and down, the object also moves up and down. But in this moment the mouse is not anymore on the handle area. I would like in this case to release the object. If I want to move it again, I should catch it again to the handle. Is this somehow possible?

**Comment by bcakmakoglu** [comment]
I think you should be able to listen to the drag-events, and, if `event.target` isn't the drag-handle element, cancel the event using `event.stopImmediatePropagation()` and `event.preventDefault()`

**Comment by SciManJD** [comment]
I think that I understand your explanation, but I didn't succeed to make it to work. How can I actually catch the suitable event? In the documentation is mentioned event onDrag, but I don't find an example how to use it. Sorry, but I need some more help...

**Comment by bcakmakoglu** [comment]
I'll try to spin up an example or some code for it, sorry been really busy so I haven't had time to explain it properly :)
I'll try to get it in here by the end of day 😄

**Comment by SciManJD** [comment]
Thanks a lot. I don't want to disturb you... but I tried many things and all of them without success.

**Comment by SciManJD** [comment]
Everything seems to be clear, but I get a wrong event. Maybe I'm listening for a wrong one. I use:
@move="onMove". Is this correct?

**Comment by bcakmakoglu** [comment]
If you're listening from a `div` element or some other HTML element and not a component the `@move` event is sent as a CustomEvent, so it should be unwrapped like this

```ts
function onMove(dragMoveEvent) {
	const event = dragMoveEvent.detail.event
}

**Comment by SciManJD** [comment]
Now I had a progress... I detect if the mouse is inside or outside the handle, but the dialog still moves when I stop changing the coordinates. I bound the position like this (I think that it is correct):

```
<div v-draggable="{handle: '.drag-handle',
        bounds: {left: dialogBounds.left, top: dialogBounds.top, right: dialogBounds.right, bottom: dialogBounds.bottom}, 
        position: {x: dialogCoordinates.x, y: dialogCoordinates.y}}" @move="onMove"> 
```

and I write the position to dialogCoordinated like this:
```
         const {x, y} = dragMoveEvent.detail.data;
         this.dialogLastCoordinates = {x: x, y: y};
```

When the mouse is outside, the function exits before these lines as it is in your example. I checked and the position doesn't change.
Nevertheless, the dialog still moves...

**Comment by bcakmakoglu** [comment]
Can you try using `disabled` instead?
My bad, I forgot that `position` will technically *not* block further dragging, it's really more useful if you need to overwrite the position instead 😅

```
const isDisabled = ref(false)

function onMove(evt) {
	if (someCond) {
		isDisabled.value = true
	} else {
		isDisabled.value = false
	}
}

<div v-draggable="{ disabled: isDisabled }">
```

**Comment by SciManJD** [comment]
The behavior is unexpected. When I drag the dialog everything is normal. When the mouse goes outside the specified bounds, the property disabled is correctly set to true and then the dialog jumps to the middle of the screen and continue moving in the same direction until the corresponding bound is reached again. Then it doesn't leave the bound, but it is still moving together with the mouse. When I release the mouse button and try to catch the dialog again and cannot move it anymore.

**Comment by SciManJD** [comment]
Just for test I set the variable isDisabled to true directly in the initialization. Then the dialog doesn't move at all. So the property disabled works, but is looks that if I continue dragging, the changed value to disabled is not applied correct and when I release the mouse button, then it is applied and I cannot move the dialog anymore.

**Comment by bcakmakoglu** [comment]
Mh... that doesn't sound right :(

Another option is to bind `move` with as an option and return true or false from it

```vue
function onControlledMove(event) {
	const dragHandle = event.target.closest(dragHandleSelector)

	if (event.target !== dragHandle) {
		return false
	}

	return true
}

<!-- We can also bind `stop` and `start` via options if we need more control -->
<div v-draggabble="{ move: onControlledMove }" @start="onStart" @stop="onStop">

**Comment by SciManJD** [comment]
This works fine. The only problem is that if I move the mouse faster, sometimes I drop the dialog and I have to catch it again. But this is another problem. Probably I have to program another condition. But thanks a lot for your help and your effort.

**Comment by bcakmakoglu** [comment]
Okay cool - if I can help you further just let me know :)
I'll close this issue for now
