### ISSUE TITLE
Typescript v4.7 TS7016 error

### ISSUE THREAD

**Issue by nesnass** [bcakmakoglu/revue-draggable#402]
**Describe the bug**
Typescript 4.7 and above reports the error:
```
error TS7016: Could not find a declaration file for module '@braks/revue-draggable'. '/Users/.../node_modules/.pnpm/@braks+revue-draggable@0.4.3_vue@3.4.21/node_modules/@braks/revue-draggable/dist/revue-draggable.es.js' implicitly has an 'any' type.
  There are types at '/Users/.../node_modules/@braks/revue-draggable/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@braks/revue-draggable' library may need to update its package.json or typings.
```

**To Reproduce**
1. Create a new vue app using `pnpm create vue@latest`
2. Add this library using `pnp i @braks/revue-draggable`
3. Import Draggable into a component `import { Draggable, DraggableEvent } from '@braks/revue-draggable'`
4. Attempt to build the application `pnpm build`

**Expected behavior**
Build should succeed by finding and including the types and source for the library from node_modules
At least a partial solution is [shown here](https://stackoverflow.com/questions/76211877/the-xxxx-library-may-need-to-update-its-package-json-or-typings-ts) where a "types" attribute is added to the library's package.json, but there is still an issue with the 'default' import (see below).

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma

**Additional context**
Note that even after adding the "types" attribute, attempting to import Draggable as default  `import Draggable, { DraggableEvent } from '@braks/revue-draggable'` prompts a different error:

```
RollupError: "default" is not exported by "node_modules/.pnpm/@braks+revue-draggable@0.4.3_vue@3.4.21/node_modules/@braks/revue-draggable/dist/revue-draggable.es.js"
```

**Comment by bcakmakoglu** [comment]
Thanks for the report.

I followed the steps to reproduce this issue on my machine but it worked fine for me. Can you give me a quick rundown of your `package.json` file or possibly a repro sandbox / repo that I could check out for direct comparison? :)

**Comment by bcakmakoglu** [comment]
Also what's your `tsconfig` file look like?
It seems like the default for `create vue` is setting `"moduleResolution": "Bundler"` which, afaik, doesn't work with TypeScript <5.

So you might have to modify your `tsconfig` file and set `"moduleResolution": "Node"` instead.

**Comment by nesnass** [comment]
Ok, the version of Typescript installed by the process described is 5.3.  Sorry, I should have stated v5 in the title but from investigations it seemed like this is something that changed in Typescript 4.7 [referred to here](https://stackoverflow.com/questions/76211877/the-xxxx-library-may-need-to-update-its-package-json-or-typings-ts#answer-76212193)

I still see the problem following the procedure in my first post. 
You can see a repo with the exact code used [here](https://github.com/nesnass/tsTest)

```
src/views/HomeView.vue:3:27 - error TS7016: Could not find a declaration file for module '@braks/revue-draggable'. '/Users/richarne/Documents/code/tsTest/node_modules/.pnpm/@braks+revue-draggable@0.4.3_vue@3.4.21/node_modules/@braks/revue-draggable/dist/revue-draggable.es.js' implicitly has an 'any' type.
  There are types at '/Users/richarne/Documents/code/tsTest/node_modules/@braks/revue-draggable/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@braks/revue-draggable' library may need to update its package.json or typings.

3 import { Draggable } from '@braks/revue-draggable'
```

Maybe your choices differed during setup?
```
✔ Project name: … tsTest
✔ Package name: … tstest
✔ Add TypeScript? … Yes
✔ Add JSX Support? … No
✔ Add Vue Router for Single Page Application development? … Yes
✔ Add Pinia for state management? … No
✔ Add Vitest for Unit Testing? … No
✔ Add an End-to-End Testing Solution? › No
✔ Add ESLint for code quality? … Yes
✔ Add Prettier for code formatting? … Yes
```

I'm also using `"type": "module"` in package.json, so need to use `NodeNext` rather than `Node` as the moduleResolution. Using `"moduleResolution": "Node"` does seem to make this error go away, but then causes lots of TS2834 errors resolving files with absolute paths, for example `import { NamedExport } from 'src/components/shared/things/NamedThing'` - very similar to [this issue here](https://github.com/vitejs/vite/issues/11552)

**Comment by bcakmakoglu** [comment]
Thanks, I'll investigate :)

**Comment by bcakmakoglu** [comment]
Should be resolved with `0.5.0`

**Comment by bcakmakoglu** [comment]
@nesnass Let me know if that worked for you 😄

**Comment by nesnass** [comment]
It does work :) The error is gone without any changes to package.json.  Thank you very much for the quick turn around.

**Comment by bcakmakoglu** [comment]
No problem :)
