### ISSUE TITLE
Move the component at the top when selected

### ISSUE THREAD

**Issue by SciManJD** [bcakmakoglu/revue-draggable#403]
Hi,
I have now many of those components. But they have predefined order, settled by z-index. I would like the component to be shown at the top when I click on it. What is the easiest way?

**Comment by SciManJD** [comment]
Hi again! Can you give me a short information if this is/will be supported or not. I just need to know if I have to find a way program it myself or there will be a standard solution. And thanks for the great job that you did up to know...

**Comment by bcakmakoglu** [comment]
Sorry I forgot to respond to this due to being hospitalized 😅

There are multiple ways to go about this
I'd think the simplest way is to use the existing class names and apply a z-index via them
'revue-draggable', 'revue-draggable-dragging', and 'revue-draggable-dragged'

In your case, you probably want to do sth like this
```css
.revue-draggable-dragging {
	z-index: 9999;
}
```

**Comment by SciManJD** [comment]
I'm sorry to here that you are hospitalized. I hope that all is ok with you. 
What you suggest is clear, but I want to let the dragged dialog on top until another is clicked/dragged, not only during the dragging But I can't always increase the z-index to the next dragged dialog. I have to return the z-index of the previously moved on the top dialog to its original value. This is what I want to achieve.

**Comment by bcakmakoglu** [comment]
Mh... how about just listening to the `start` drag-event and adding a style/class to the element (should be available as `data.node`)?
You could put the element into a ref and when the `start` event is called again, just remove the style/class from the previous element and add it to the next one.

Or you could just use a simpler version with css only and apply the z-index when the element is being dragged *or* has focus
```css
.revue-draggable-dragging, revue-draggable:focus {
	z-index: 9999;
}
```

**Comment by bcakmakoglu** [comment]
I think a small combination of both should work fine here.

```vue
<script setup>
import { ref } from 'vue'
import { Draggable } from '@braks/revue-draggable'

const prevNode = ref(null)

function onStart(event) {
  if (prevNode.value) {
    prevNode.value.style.zIndex = ''
  }

  const node = event.data.node
  node.style.zIndex = 9999
  prevNode.value = node
}
</script>

<template>
  <div style="height: 100vh">
    <Draggable @start="onStart">
      <div class="box">Box1</div>
    </Draggable>

    <Draggable @start="onStart">
      <div class="box">Box2</div>
    </Draggable>
  </div>
</template>

<style>
.revue-draggable {
  position: relative;
}

.revue-draggable-dragging {
  z-index: 9999;
}

.box {
  /* box styles */
}
</style>

**Comment by SciManJD** [comment]
Thanks a lot. This example works fine. But my situation is more complicated. My dialogs can be opened and closed. When a new dialog is opened, I would like to put it in front. This is not a problem, but in this moment I don't have a reference to the dialog that is currently in front. 
I made it in another way. I don't know if it good enough, but it works. When I create a new dialog, it applies a class that sets the z-index to a bigger value. In the same time this dialog sends an event to the other dialogs that it is currently in front. The other dialogs accept this event and remove the class that sets the z-index to a higher value, so they go to back.

**Comment by bcakmakoglu** [comment]
Sounds good enough to me 😄 
If it works and is maintainable, then it's good enough imo :)

**Comment by SciManJD** [comment]
Thanks a lot for the help!

**Comment by bcakmakoglu** [comment]
No problem, glad we could resolve this 😄
