### ISSUE TITLE
Specify element to be the 'drag handle'

### ISSUE THREAD

**Issue by jfrueh** [bcakmakoglu/revue-draggable#52]
If you make an element draggable that has inputs in it (like a text box for example), the element drags when the user uses their mouse to highlight text in the textbox.  

I'd like to propose being able to specify an element that the user clicks on to initiate the dragging.  This would allow for the creation of a drag handle.

Please see the attached image.  Blue arrow is pointing to the element that would be pressed to initiate drag.  As of now, when you put the mouse in the input box and highlight text the entire element drags (not desirable).

![image](https://user-images.githubusercontent.com/1854052/129452585-88a0c6a1-8e5c-4f33-a2a2-5ce60a89743d.png)

**Comment by bcakmakoglu** [comment]
There already is an option to specify a drag handle element.
You can just pass it as an option to the directive. 

Example:
```vue
<div v-draggable="{ handle: 'strong' }">
   <p>this is not draggable</p>
   <strong>this is draggable</strong>
</div>
```

or
```vue
<div v-draggable="{ handle: '.handle' }">
   <p>this is not draggable</p>
   <div class="handle">this is draggable</strong>
</div>
```

**Comment by jfrueh** [comment]
Sorry, missed that in the docs.  Works perfectly.
