### ISSUE TITLE
Default position doesn't work

### ISSUE THREAD

**Issue by futurfuturfuturfutur** [bcakmakoglu/revue-draggable#96]
**Describe the bug**
Default position option doesn't work

**To Reproduce**
1. Set default possition through :default-position="{ x: 500, y: 500 }"
2. Load the page
3. Draggable appears on x0 y0

**Expected behavior**
It should be on x500 y500

**Comment by bcakmakoglu** [comment]
Thanks for opening an issue, I'll check it out and will get back to you asap 💪

**Comment by bcakmakoglu** [comment]
Can you give more info on the version you're using?

This [example](https://codesandbox.io/s/vue3-vite-forked-npy3v?file=/App.vue) also seems to be working without an issue (vue3).

A code snippet or something would probably help me identify the issue ☺️

**Comment by futurfuturfuturfutur** [comment]
My vue version is 3.2.11
After your response just I've tried to reinstall package, after that everything works like a charm. So, in case of similar behavior just try to reinstall.
